### ISSUE TITLE
Please "preserve and archive" ctrtransfer images one last time instead of just not seeding anymore

### ISSUE THREAD

**Issue by coldeny** [adrifcastr/3Down#6]
Contacting you through disord or gmail is impossible. Let me write here.

Seems like you won't seed torrents anymore (def. makes sense) but why wouldn't you preserve and archive them on [archive.org](http://archive.org/) for a longer future of these files? 

(yes, i tried to get those files because my 9.2U breaks luma3ds latest version with generic home 15 error.)

@castdrian (idk if you get notification otherwise, i dont know much about github)

**Comment by castdrian** [comment]
there's no longer any use for this ever since the boot9 bootrom has been successfully dumped.
